SELECT ZUTAT.BEZEICHNUNG, REZEPT.NAME
FROM ZUTAT
INNER JOIN REZEPTZUTAT ON ZUTAT.ZUTATENNR = REZEPTZUTAT.ZUTATENNR
INNER JOIN REZEPT ON REZEPTZUTAT.REZEPTNR = REZEPT.REZEPTNR
WHERE ZUTAT.BEZEICHNUNG = 'Mozzarella';