SELECT
    zutat.BEZEICHNUNG,
    LIEFERANT.LIEFERANTENNAME,
    region.PLZ,
    region.ORT
FROM
    zutat
INNER JOIN LIEFERANT ON zutat.LIEFERANT = LIEFERANT.LIEFERANTENNR
INNER JOIN region ON LIEFERANT.REGIONSNR = region.REGIONSNR
WHERE
    zutat.BEZEICHNUNG = 'Kartoffel';